version: "3"

services:
  db:
    image: mongo:latest
    container_name: "ms2019-db"
    volumes:
      - ./docker/db/volumes:/data/db
      - ./docker/db/seeds:/seeds
    ports:
      - "37017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: "ms2019-db-gui"
    links:
      - "db:mongo"
    ports:
      - "8081:8081"
    restart: always

  redis:
    image: redis:latest
    container_name: "ms2019-redis"
    ports:
      - "7379:6379"
    command: redis-server

  web:
    build: "."
    container_name: "ms2019-web"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis